//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSWebTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForumMessageLexi
    {
        public long ForumMessageId { get; set; }
        public int SentenceIndex { get; set; }
        public int WordIndex { get; set; }
        public Nullable<int> ParentWordIndex { get; set; }
        public string POS { get; set; }
        public string NER { get; set; }
        public string Word { get; set; }
        public string LongWord { get; set; }
    
        public virtual ForumMessage ForumMessage { get; set; }
    }
}
