//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSWebTool.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SHPEntities : DbContext
    {
        public SHPEntities()
            : base("name=SHPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ForumMessageKeyword> ForumMessageKeywords { get; set; }
        public virtual DbSet<ForumMessageLexi> ForumMessageLexis { get; set; }
        public virtual DbSet<ForumMessage> ForumMessages { get; set; }
        public virtual DbSet<ForumMessageTag> ForumMessageTags { get; set; }
        public virtual DbSet<ForumUser> ForumUsers { get; set; }
    }
}
