//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumUserUpdateService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForumMember
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ForumMember()
        {
            this.ForumMemberActivities = new HashSet<ForumMemberActivity>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public System.DateTime MemberSince { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ForumMemberActivity> ForumMemberActivities { get; set; }
    }
}
