//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPIISUnanswered.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASPIISThread
    {
        public int Id { get; set; }
        public string ThreadId { get; set; }
        public System.DateTime PostDate { get; set; }
        public string Title { get; set; }
        public string Link { get; set; }
        public int forumId { get; set; }
        public bool IsLastOp { get; set; }
    
        public virtual ASPIISForum ASPIISForum { get; set; }
    }
}
