//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPIISUnanswered.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Engineer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Engineer()
        {
            this.Products = new HashSet<Product>();
        }
    
        public string MSAlias { get; set; }
        public string Chinese { get; set; }
        public System.DateTime OnBoardDate { get; set; }
        public Nullable<System.DateTime> GoLiveDate { get; set; }
        public string ReadinessPool { get; set; }
        public int EID { get; set; }
        public string DisplayName { get; set; }
        public string PhoneNumber { get; set; }
        public string Project { get; set; }
        public string WSAlias { get; set; }
        public int SubTeamId { get; set; }
    
        public virtual Team Team { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}
