//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPIISUnanswered.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WSWebToolEntities : DbContext
    {
        public WSWebToolEntities()
            : base("name=WSWebToolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<ASPIISForum> ASPIISForums { get; set; }
        public virtual DbSet<Engineer> Engineers { get; set; }
        public virtual DbSet<EscalatedThread> EscalatedThreads { get; set; }
        public virtual DbSet<FollowUpThread> FollowUpThreads { get; set; }
        public virtual DbSet<Forum> Forums { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<ThreadNote> ThreadNotes { get; set; }
        public virtual DbSet<ASPIISThread> ASPIISThreads { get; set; }
    }
}
