//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumUsers.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASPIISForum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ASPIISForum()
        {
            this.ASPIISThreads = new HashSet<ASPIISThread>();
        }
    
        public int Id { get; set; }
        public int ForumId { get; set; }
        public string ForumName { get; set; }
        public int ProductId { get; set; }
    
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASPIISThread> ASPIISThreads { get; set; }
    }
}
