//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumUsers.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FollowUpThread
    {
        public string ThreadId { get; set; }
        public string cat_msalias { get; set; }
        public string ThreadName { get; set; }
        public string cat_URL { get; set; }
        public System.DateTime LastOP { get; set; }
        public int ProductId { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
