//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumUsers.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForumMemberActuvity
    {
        public int Id { get; set; }
        public string ForumMemberId { get; set; }
        public string Activity { get; set; }
        public string Detail { get; set; }
        public System.DateTime Time { get; set; }
    
        public virtual ForumMember ForumMember { get; set; }
    }
}
