//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumUsers.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForumMessage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ForumMessage()
        {
            this.ForumMessageKeywords = new HashSet<ForumMessageKeyword>();
            this.ForumMessageLexis = new HashSet<ForumMessageLexi>();
            this.ForumMessageTags = new HashSet<ForumMessageTag>();
        }
    
        public long Id { get; set; }
        public int Type { get; set; }
        public string MessageId { get; set; }
        public string PostMessageId { get; set; }
        public Nullable<bool> AnalysisCompleted { get; set; }
        public long AnalysisProgress { get; set; }
        public int ViewCount { get; set; }
        public int ReplyCount { get; set; }
        public bool IsAnswered { get; set; }
        public int Score { get; set; }
        public Nullable<int> FavoriteCount { get; set; }
        public Nullable<int> UpVoteCount { get; set; }
        public Nullable<int> DownVoteCount { get; set; }
        public Nullable<int> DeleteVoteCount { get; set; }
        public long CreatedTime { get; set; }
        public Nullable<long> CreatedTimeOfHourly { get; set; }
        public Nullable<long> CreatedTimeOfDaily { get; set; }
        public long LastUpdatedTime { get; set; }
        public string OwnerId { get; set; }
        public string Title { get; set; }
        public string URL { get; set; }
        public int LCID { get; set; }
        public string Country { get; set; }
        public string Location { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public string Content { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ForumMessageKeyword> ForumMessageKeywords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ForumMessageLexi> ForumMessageLexis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ForumMessageTag> ForumMessageTags { get; set; }
        public virtual ForumUser ForumUser { get; set; }
    }
}
