//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumUsers.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSDNThread
    {
        public int Id { get; set; }
        public string ThreadId { get; set; }
        public System.DateTime PostDate { get; set; }
        public string Title { get; set; }
        public string Link { get; set; }
        public bool IsLastOp { get; set; }
        public bool IsAnswered { get; set; }
        public string Product { get; set; }
    }
}
